---
apiVersion: v1
kind: Service
metadata:
  name: example-gossip
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: example
  ports:
    - protocol: TCP
      name: reliable
      port: 7946
    - protocol: UDP
      name: best-effort
      port: 7946
---
apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: example
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app.kubernetes.io/name: example
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example
    spec:
      containers:
        - name: example
          image: gedcb/example:latest
          command:
            - "bin/example"
          args:
            - "-address=$(NODE_ADDRESS)"
            - "-cluster=example-gossip"
            - "-gossipPort=7946"
            - "-httpPort=8080"
          env:
            - name: NODE_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - protocol: TCP
              name: http
              containerPort: 8080
            - protocol: TCP
              name: reliable
              containerPort: 7946
            - protocol: UDP
              name: best-effort
              containerPort: 7946
