---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app.kubernetes.io/name: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example
    spec:
      containers:
        - name: example
          image: gedcb/example:latest
---
apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  type: ClusterIP
  clusterIP: "None"
  selector:
    app.kubernetes.io/name: example
  ports:
    - protocol: TCP
      port: 7946
      targetPort: 7946
    - protocol: UDP
      port: 7946
      targetPort: 7946