---
apiVersion: v1
kind: Service
metadata:
  name: seed
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: seed
  ports:
    - protocol: TCP
      name: reliable
      port: 7946
    - protocol: UDP
      name: best-effort
      port: 7946
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seed
  labels:
    app.kubernetes.io/name: seed
spec:
  replicas: 4
  serviceName: seed
  selector:
    matchLabels:
      app.kubernetes.io/name: seed
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seed
    spec:
      containers:
        - name: seed
          image: gedcb
          imagePullPolicy: IfNotPresent
          command:
            - "bin/seed"
          args:
            - "-seed=seed-0.seed.default.svc.cluster.local"
            - "-seed=seed-1.seed.default.svc.cluster.local"
            - "-seed=seed-2.seed.default.svc.cluster.local"
            - "-cluster=seed-gossip"
            - "-gossipPort=7946"
            - "-httpPort=8080"
          ports:
            - protocol: TCP
              name: http
              containerPort: 8080
            - protocol: TCP
              name: reliable
              containerPort: 7946
            - protocol: UDP
              name: best-effort
              containerPort: 7946
          readinessProbe:
            httpGet:
              path: /
              port: http